export const ADD_SNACK_INGREDIENT = 'ADD_SNACK_INGREDIENT';
export const REMOVE_SNACK_INGREDIENT = 'REMOVE_SNACK_INGREDIENT';
export const SET_SNACK_INGREDIENTS = 'SET_SNACK_INGREDIENTS';
export const FETCH_SNACK_INGREDIENTS_FAILED = 'FETCH_SNACK_INGREDIENTS_FAILED';
export const INIT_SNACK_INGREDIENTS = 'INIT_SNACK_INGREDIENTS';
export const SNACK_BUILD_INIT = 'SNACK_BUILD_INIT';

export const PURCHASE_SNACK_START = 'PURCHASE_SNACK_START';
export const PURCHASE_SNACK_SUCCESS = 'PURCHASE_SNACK_SUCCESS';
export const PURCHASE_SNACK_FAIL = 'PURCHASE_SNACK_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_SNACK = 'PURCHASE_SNACK';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS = 'FETCH_ORDERS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';