export const ADD_BURGER_INGREDIENT = 'ADD_BURGER_INGREDIENT';
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT';
export const SET_BURGER_INGREDIENTS = 'SET_BURGER_INGREDIENTS';
export const FETCH_BURGER_INGREDIENTS_FAILED = 'FETCH_BURGER_INGREDIENTS_FAILED';
export const INIT_BURGER_INGREDIENTS = 'INIT_BURGER_INGREDIENTS';
export const BURGER_BUILD_INIT = 'BURGER_BUILD_INIT';

export const ADD_PIZZA_INGREDIENT = 'ADD_PIZZA_INGREDIENT';
export const REMOVE_PIZZA_INGREDIENT = 'REMOVE_PIZZA_INGREDIENT';
export const SET_PIZZA_INGREDIENTS = 'SET_PIZZA_INGREDIENTS';
export const FETCH_PIZZA_INGREDIENTS_FAILED = 'FETCH_PIZZA_INGREDIENTS_FAILED';
export const INIT_PIZZA_INGREDIENTS = 'INIT_PIZZA_INGREDIENTS';
export const PIZZA_BUILD_INIT = 'PIZZA_BUILD_INIT';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS = 'FETCH_ORDERS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';